### ISSUE TITLE
Problem with internal links and the ref shortcut

### ISSUE THREAD

**Issue by pprevos** [niklasfasching/go-org#51]
Internal links stopped working (Hugo version: `hugo v0.81.0+extended linux/amd64 BuildDate=unknown`).

I use `{{< ref filename.org >}}` for internal links. For some reason, Hugo now adds `../` to the front of the HTML link.

`{{< ref filename.org >}}` resolves properly to `https://baseurl/filename/`

But when I surround it with square brackets, it goes wrong:

`[[{{< ref filename.org >}}][link text]]` resolves to `../https://baseurl/filename/`.

Everything works fine when using Markdown.

**Comment by niklasfasching** [comment]
Interesting!
Apparently hugo [replaces shortcodes](https://github.com/gohugoio/hugo/commit/55fcd2f30f4358a800932aa60160935c0c22f96d/) with [placeholders](https://github.com/gohugoio/hugo/blob/97934779ededfcfef0ee2621e7dacad0127ef4b5/hugolib/shortcode.go#L159) before sending the markup to the renderer. 

To go-org `[[{{< ref filename.org >}}][link text]]` looks like `[[HAHAHUGOSHORTCODE-s0-HBHB][link text]]`. 
This conflicts with the recent introduction of [pretty relative links](https://github.com/niklasfasching/go-org/commit/5dadf8c/), which tries to be clever and rewrites link urls to make relative links  work with [hugo pretty urls](https://gohugo.io/content-management/urls/#pretty-urls).

I guess we could just not prettify links starting with `HAHAHUGOSHORTCODE`. Maybe there's a better solution - I'll think about it some more first

**Comment by pprevos** [comment]
Thanks for looking into this issue.

Using `[[filename.org][link text]]` works only without extension and when the post slug is the same as the filename. Ideally, proper Org Mode file links should be resolved. 

Shortcodes have the advantage that Hugo searches for the file if it is not in the same folder and resolves to the slug instead of the filename.

Interestingly, '[[{{% ref markdown %}}][test]]` works as it used to.

The [Hugo documentation states](https://gohugo.io/content-management/shortcodes/) that "The `<` character indicates that the shortcode’s inner content does not need further rendering."

I could easily do a search and replace across my sites.

**Comment by niklasfasching** [comment]
Makes sense, thx for the explanation. 
If replacing is an option I'd prefer that to keep the amount of hugo specific code in go-org to a minimum. If you run into any problems with that just re-open / comment and I'll add the pretty url exception for `HAHAHUGOSHORTCODE`.  Closing for now

**Comment by pprevos** [comment]
I replaced all shortcodes and it seems to work.

**Comment by pprevos** [comment]
Hi Niklas, 

I just published a detailed blog post on how to use native Org-Mode support in Hugo to publish websites: https://lucidmanager.org/productivity/create-websites-with-org-mode-and-hugo/

Thanks for maintaining go-org.

Peter

**Comment by natrys** [comment]
Hi @pprevos , mind if I ask if you got relative linking to `static/` working without sacrificing image preview?

I am writing some R code, I am asking it to produce plots by doing something like:

```
#+begin_src R :results graphics file :output-dir "../../static/plots/" :file test.png
library(ggplot2)
....
#+end_src
```

This way I can see generated plot right in org buffer which is very useful, but generated image source still has the `/static/` part in it which, as you said in the blogpost, hugo for some reason insists on stripping in the published output.

-----

Also would like to ask @niklasfasching, could the above situation be handled unrelated to the broken PrettyRelativeLinks feature? Maybe as special case only for stripping `assetDir` fragment from the relative url if it exists? Failing that, do you know of any way `assetDir` top level could be stopped from being stripped in the published output by Hugo?

**Comment by natrys** [comment]
Sigh, right after I finally ask for help, I stumble upon the answer. I still don't understand modules, but this did the job:

``` toml
[[module.mounts]]
  source="static"
  target="static/static"
  includeFiles = ["plots/*"]
```

This way, hugo now preserves the top-level `static/`, and both preview and publish works.

**Comment by pprevos** [comment]
This is an issue for Hugo both in Org mode and Markdown, so it is a [Hugo issue,](https://stackoverflow.com/questions/69271714/image-in-hugo-markdown-not-showing) not specific to go-org.
